<h1 class="title">QUnhandledException Class</h1>  <p>The QUnhandledException class represents an unhandled exception in a Qt Concurrent worker thread. <a href="#details">More...</a></p>  <table class="alignedsummary"> <tr>
<td class="memItemLeft rightAlign topAlign"> Header:</td>
<td class="memItemRight bottomAlign"> <span class="preprocessor">#include &lt;QUnhandledException&gt;</span> </td>
</tr>
<tr>
<td class="memItemLeft rightAlign topAlign"> CMake:</td>
<td class="memItemRight bottomAlign"> find_package(Qt6 COMPONENTS Core REQUIRED)  target_link_libraries(mytarget PRIVATE Qt6::Core)</td>
</tr>
<tr>
<td class="memItemLeft rightAlign topAlign"> qmake:</td>
<td class="memItemRight bottomAlign"> QT += core</td>
</tr>
<tr>
<td class="memItemLeft rightAlign topAlign"> Since:</td>
<td class="memItemRight bottomAlign"> Qt 5.0</td>
</tr>
<tr>
<td class="memItemLeft rightAlign topAlign"> Inherits:</td>
<td class="memItemRight bottomAlign"> <a href="qexception.html">QException</a>
</td>
</tr>
</table> <ul> <li><a href="https://doc.qt.io/qt-6.2/qunhandledexception-members.html">List of all members, including inherited members</a></li> </ul> <h2 id="public-functions">Public Functions
</h2> <table class="alignedsummary"> <tr>
<td class="memItemLeft rightAlign topAlign"> </td>
<td class="memItemRight bottomAlign">
<b><a href="qunhandledexception.html#QUnhandledException-2">QUnhandledException</a></b>(const QUnhandledException &amp;<i>other</i>)</td>
</tr> <tr>
<td class="memItemLeft rightAlign topAlign"> </td>
<td class="memItemRight bottomAlign">
<b><a href="qunhandledexception.html#QUnhandledException-1">QUnhandledException</a></b>(QUnhandledException &amp;&amp;<i>other</i>)</td>
</tr> <tr>
<td class="memItemLeft rightAlign topAlign"> </td>
<td class="memItemRight bottomAlign">
<b><a href="qunhandledexception.html#QUnhandledException">QUnhandledException</a></b>(std::exception_ptr <i>exception</i> = nullptr)</td>
</tr> <tr>
<td class="memItemLeft rightAlign topAlign"> QUnhandledException &amp;</td>
<td class="memItemRight bottomAlign">
<b><a href="qunhandledexception.html#operator-eq-1">operator=</a></b>(const QUnhandledException &amp;<i>other</i>)</td>
</tr> <tr>
<td class="memItemLeft rightAlign topAlign"> std::exception_ptr </td>
<td class="memItemRight bottomAlign">
<b><a href="qunhandledexception.html#exception">exception</a></b>() const</td>
</tr> <tr>
<td class="memItemLeft rightAlign topAlign"> void </td>
<td class="memItemRight bottomAlign">
<b><a href="qunhandledexception.html#swap">swap</a></b>(QUnhandledException &amp;<i>other</i>)</td>
</tr> </table>   <h2 id="details">Detailed Description
</h2> <p>If a worker thread throws an exception that is not a subclass of <a href="qexception.html">QException</a>, the <a href="qtconcurrent-index.html">Qt Concurrent</a> functions will throw a QUnhandledException on the receiver thread side. The information about the actual exception that has been thrown will be saved in the QUnhandledException class and can be obtained using the <a href="qunhandledexception.html#exception">exception</a>() method. For example, you can process the exception held by QUnhandledException in the following way:</p> <pre data-language="cpp">try {
    auto f = QtConcurrent::run([] { throw MyException {}; });
    // ...
} catch (const QUnhandledException &amp;e) {
    try {
        if (e.exception())
            std::rethrow_exception(e.exception());
    } catch (const MyException &amp;ex) {
        // Process 'ex'
    }
}</pre> <p>Inheriting from this class is not supported.</p>    <h2>Member Function Documentation</h2>  <h3 class="fn" id="QUnhandledException-2">QUnhandledException::<span class="name">QUnhandledException</span>(const <span class="type"><a href="qunhandledexception.html#QUnhandledException">QUnhandledException</a></span> &amp;<i>other</i>)
</h3> <p>Constructs a QUnhandledException object as a copy of <i>other</i>.</p>   <h3 class="fn" id="QUnhandledException-1">QUnhandledException::<span class="name">QUnhandledException</span>(<span class="type"><a href="qunhandledexception.html#QUnhandledException">QUnhandledException</a></span> &amp;&amp;<i>other</i>)
</h3> <p>Move-constructs a QUnhandledException, making it point to the same object as <i>other</i> was pointing to.</p>   <h3 class="fn" id="QUnhandledException">
<code>[since 6.0] </code>QUnhandledException::<span class="name">QUnhandledException</span>(<span class="type">std::exception_ptr</span> <i>exception</i> = nullptr)
</h3> <p>Constructs a new QUnhandledException object. Saves the pointer to the actual exception object if <i>exception</i> is passed.</p> <p>This function was introduced in Qt 6.0.</p> <p><b>See also </b><a href="qunhandledexception.html#exception">exception</a>().</p>   <h3 class="fn" id="operator-eq-1">
<span class="type"><a href="qunhandledexception.html#QUnhandledException">QUnhandledException</a></span> &amp;QUnhandledException::<span class="name">operator=</span>(const <span class="type"><a href="qunhandledexception.html#QUnhandledException">QUnhandledException</a></span> &amp;<i>other</i>)
</h3> <p>Assigns <i>other</i> to this <a href="qunhandledexception.html">QUnhandledException</a> object and returns a reference to this <a href="qunhandledexception.html">QUnhandledException</a> object.</p>   <h3 class="fn" id="exception">
<code>[since 6.0] </code><span class="type">std::exception_ptr</span> QUnhandledException::<span class="name">exception</span>() const
</h3> <p>Returns a <a href="https://en.cppreference.com/w/cpp/error/exception_ptr">pointer</a> to the actual exception that has been saved in this <a href="qunhandledexception.html">QUnhandledException</a>. Returns a <code>null</code> pointer, if it does not point to an exception object.</p> <p>This function was introduced in Qt 6.0.</p>   <h3 class="fn" id="swap">
<code>[since 6.0] </code><span class="type">void</span> QUnhandledException::<span class="name">swap</span>(<span class="type"><a href="qunhandledexception.html#QUnhandledException">QUnhandledException</a></span> &amp;<i>other</i>)
</h3> <p>Swaps this <a href="qunhandledexception.html">QUnhandledException</a> with <i>other</i>. This function is very fast and never fails.</p> <p>This function was introduced in Qt 6.0.</p><div class="_attribution">
  <p class="_attribution-p">
    &copy; The Qt Company Ltd<br>Licensed under the GNU Free Documentation License, Version 1.3.<br>
    <a href="https://doc.qt.io/qt-6.2/qunhandledexception.html" class="_attribution-link">https://doc.qt.io/qt-6.2/qunhandledexception.html</a>
  </p>
</div>
