    <h1 id="firstHeading" class="firstHeading">std::nested_exception</h1>            <table class="t-dcl-begin"> <tr class="t-dsc-header"> <th> Defined in header <code><a href="../header/exception.html" title="cpp/header/exception">&lt;exception&gt;</a></code> </th> <th> </th> <th> </th> </tr> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">class nested_exception;</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> </td> </tr>  </table> <p><code>std::nested_exception</code> is a polymorphic mixin class which can capture and store the current exception, making it possible to nest exceptions of arbitrary types within each other.</p>
<h3 id="Member_functions"> Member functions</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="nested_exception/nested_exception.html" title="cpp/error/nested exception/nested exception"> <span class="t-lines"><span>(constructor)</span></span></a></div> </td> <td> constructs a nested_exception <br> <span class="t-mark">(public member function)</span> </td>
</tr> <tr class="t-dsc"> <td> <div><a href="nested_exception/~nested_exception.html" title="cpp/error/nested exception/~nested exception"> <span class="t-lines"><span>(destructor)</span></span></a></div>
<div><span class="t-lines"><span><span class="t-cmark">[virtual]</span></span></span></div> </td> <td> destructs a nested exception <br> <span class="t-mark">(virtual public member function)</span> </td>
</tr> <tr class="t-dsc"> <td> <div><a href="nested_exception/operator=.html" title="cpp/error/nested exception/operator="> <span class="t-lines"><span>operator=</span></span></a></div> </td> <td> replaces the contents of a nested_exception <br> <span class="t-mark">(public member function)</span> </td>
</tr> <tr class="t-dsc"> <td> <div><a href="nested_exception/rethrow_nested.html" title="cpp/error/nested exception/rethrow nested"> <span class="t-lines"><span>rethrow_nested</span></span></a></div> </td> <td> throws the stored exception <br> <span class="t-mark">(public member function)</span> </td>
</tr> <tr class="t-dsc"> <td> <div><a href="nested_exception/nested_ptr.html" title="cpp/error/nested exception/nested ptr"> <span class="t-lines"><span>nested_ptr</span></span></a></div> </td> <td> obtains a pointer to the stored exception <br> <span class="t-mark">(public member function)</span> </td>
</tr> </table> <h3 id="Non-member_functions"> Non-member functions</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="throw_with_nested.html" title="cpp/error/throw with nested"> <span class="t-lines"><span>throw_with_nested</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> throws its argument with <code>std::nested_exception</code> mixed in <br> <span class="t-mark">(function template)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="rethrow_if_nested.html" title="cpp/error/rethrow if nested"> <span class="t-lines"><span>rethrow_if_nested</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> throws the exception from a <code>std::nested_exception</code> <br> <span class="t-mark">(function template)</span>  </td>
</tr> </table> <h3 id="Example"> Example</h3> 
<div class="t-example">
<p>Demonstrates construction and recursion through a nested exception object.</p>
<div class="cpp source-cpp"><pre data-language="cpp">#include &lt;exception&gt;
#include &lt;fstream&gt;
#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
#include &lt;string&gt;
 
// prints the explanatory string of an exception. If the exception is nested,
// recurses to print the explanatory of the exception it holds
void print_exception(const std::exception&amp; e, int level =  0)
{
    std::cerr &lt;&lt; std::string(level, ' ') &lt;&lt; "exception: " &lt;&lt; e.what() &lt;&lt; '\n';
    try
    {
        std::rethrow_if_nested(e);
    }
    catch (const std::exception&amp; nestedException)
    {
        print_exception(nestedException, level + 1);
    }
    catch (...) {}
}
 
// sample function that catches an exception and wraps it in a nested exception
void open_file(const std::string&amp; s)
{
    try
    {
        std::ifstream file(s);
        file.exceptions(std::ios_base::failbit);
    }
    catch (...)
    {
        std::throw_with_nested(std::runtime_error("Couldn't open " + s));
    }
}
 
// sample function that catches an exception and wraps it in a nested exception
void run()
{
    try
    {
        open_file("nonexistent.file");
    }
    catch (...)
    {
        std::throw_with_nested(std::runtime_error("run() failed"));
    }
}
 
// runs the sample function above and prints the caught exception
int main()
{
    try
    {
        run();
    }
    catch (const std::exception&amp; e)
    {
        print_exception(e);
    }
}</pre></div> <p>Possible output:</p>
<div class="text source-text"><pre data-language="c">exception: run() failed
 exception: Couldn't open nonexistent.file
  exception: basic_ios::clear</pre></div> </div> <h3 id="See_also"> See also</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="exception_ptr.html" title="cpp/error/exception ptr"> <span class="t-lines"><span>exception_ptr</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> shared pointer type for handling exception objects <br> <span class="t-mark">(typedef)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="throw_with_nested.html" title="cpp/error/throw with nested"> <span class="t-lines"><span>throw_with_nested</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> throws its argument with <code>std::nested_exception</code> mixed in <br> <span class="t-mark">(function template)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="rethrow_if_nested.html" title="cpp/error/rethrow if nested"> <span class="t-lines"><span>rethrow_if_nested</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> throws the exception from a <code>std::nested_exception</code> <br> <span class="t-mark">(function template)</span>  </td>
</tr> </table>           <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/error/nested_exception" class="_attribution-link">https://en.cppreference.com/w/cpp/error/nested_exception</a>
  </p>
</div>
