<h1 id="class-PTY::ChildExited" class="class"> class PTY::ChildExited </h1>
<dl class="meta">
<dt>Parent:</dt>
<dd class="meta-parent"><a href="../runtimeerror.html">RuntimeError</a></dd>
</dl> <section class="description"> <p>Thrown when <a href="../pty.html#method-c-check"><code>PTY::check</code></a> is called for a pid that represents a process that has exited.</p> </section> <section id="5Buntitled-5D" class="documentation-section"> <section id="public-instance-5Buntitled-5D-method-details" class="method-section"> <header> <h3>Public Instance Methods</h3> </header> <div class="method-detail "> <div class="method-header"> <div class="method-heading" id="method-i-status"> <span class="method-name">status</span><span class="method-args">()</span> <a class="method-click-advice">Show source</a> </div> </div> <div class="method-description">
<div class="method-source-code" id="status-source"> <pre class="c" data-language="c">static VALUE
echild_status(VALUE self)
{
    return rb_ivar_get(self, rb_intern("status"));
}</pre> </div> <p>Returns the exit status of the child for which PTY#check raised this exception</p>  </div> </div> </section> </section><div class="_attribution">
  <p class="_attribution-p">
    Ruby Core &copy; 1993&ndash;2022 Yukihiro Matsumoto<br>Licensed under the Ruby License.<br>Ruby Standard Library &copy; contributors<br>Licensed under their own licenses.<br>
    
  </p>
</div>
