    <h1 id="firstHeading" class="firstHeading">std::terminate</h1>            <table class="t-dcl-begin"> <tr class="t-dsc-header"> <th> Defined in header <code><a href="../header/exception.html" title="cpp/header/exception">&lt;exception&gt;</a></code> </th> <th> </th> <th> </th> </tr>   <tr class="t-dcl t-until-cxx11"> <td><pre data-language="cpp">void terminate();</pre></td> <td class="t-dcl-nopad"> </td> <td><span class="t-mark-rev t-until-cxx11">(until C++11)</span></td> </tr> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">[[noreturn]] void terminate() noexcept;</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> </td> </tr>   </table> <p><code>std::terminate()</code> is called by the C++ runtime when the program cannot continue for any of the following reasons:</p>
<div class="t-li1">
<span class="t-li">1)</span> an <a href="../language/throw.html" title="cpp/language/throw">exception is thrown</a> and not caught (it is implementation-defined whether any stack unwinding is done in this case)</div> <div class="t-li1">
<span class="t-li">2)</span> a function directly invoked by the exception handling mechanism while handling an exception that has not yet been caught exits via an exception (e.g. a destructor of some local object, or a copy constructor constructing a catch-clause parameter)</div> <div class="t-li1">
<span class="t-li">3)</span> the constructor or the destructor of a static <span class="t-rev-inl t-since-cxx11"><span>or thread-local</span><span><span class="t-mark-rev t-since-cxx11">(since C++11)</span></span></span> object throws an exception</div> <div class="t-li1">
<span class="t-li">4)</span> a function registered with <code><a href="../utility/program/atexit.html" title="cpp/utility/program/atexit">std::atexit</a></code> <span class="t-rev-inl t-since-cxx11"><span>or <code><a href="../utility/program/at_quick_exit.html" title="cpp/utility/program/at quick exit">std::at_quick_exit</a></code></span><span><span class="t-mark-rev t-since-cxx11">(since C++11)</span></span></span> throws an exception</div> <table class="t-rev-begin"> <tr class="t-rev t-until-cxx17">
<td> <span class="t-li">5)</span> a <a href="../language/except_spec.html" title="cpp/language/except spec">dynamic exception specification</a> is violated and the default handler for <code><a href="unexpected.html" title="cpp/error/unexpected">std::unexpected</a></code> is executed <span class="t-li">6)</span> a non-default handler for <code><a href="unexpected.html" title="cpp/error/unexpected">std::unexpected</a></code> throws an exception that violates the previously violated dynamic exception specification, if the specification does not include <code><a href="bad_exception.html" title="cpp/error/bad exception">std::bad_exception</a></code> </td> <td><span class="t-mark-rev t-until-cxx17">(until C++17)</span></td>
</tr> </table> <table class="t-rev-begin"> <tr class="t-rev t-since-cxx11">
<td> <span class="t-li">7)</span> a <a href="../language/noexcept_spec.html" title="cpp/language/noexcept spec">noexcept specification</a> is violated (it is implementation-defined whether any stack unwinding is done in this case) <span class="t-li">8)</span> <code><a href="nested_exception/rethrow_nested.html" title="cpp/error/nested exception/rethrow nested">std::nested_exception::rethrow_nested</a></code> is called for an object that isn't holding a captured exception <span class="t-li">9)</span> an exception is thrown from the initial function of <code><a href="../thread/thread.html" title="cpp/thread/thread">std::thread</a></code> <span class="t-li">10)</span> a joinable <code><a href="../thread/thread.html" title="cpp/thread/thread">std::thread</a></code> is destroyed or assigned to <span class="t-li">11)</span> <code><a href="../thread/condition_variable/wait.html" title="cpp/thread/condition variable/wait">std::condition_variable::wait</a></code>, <code><a href="../thread/condition_variable/wait_until.html" title="cpp/thread/condition variable/wait until">std::condition_variable::wait_until</a></code>, or <code><a href="../thread/condition_variable/wait_for.html" title="cpp/thread/condition variable/wait for">std::condition_variable::wait_for</a></code> fails to reach its postcondition (e.g. if relocking the mutex throws) </td> <td><span class="t-mark-rev t-since-cxx11">(since C++11)</span></td>
</tr> </table> <table class="t-rev-begin"> <tr class="t-rev t-since-cxx17">
<td> <span class="t-li">12)</span> a function invoked by a <a href="../algorithm.html" title="cpp/algorithm">parallel algorithm</a> exits via an uncaught exception and the <a href="../algorithm/execution_policy_tag_t.html" title="cpp/algorithm/execution policy tag t">execution policy</a> specifies termination. </td> <td><span class="t-mark-rev t-since-cxx17">(since C++17)</span></td>
</tr> </table> <p><code>std::terminate()</code> may also be called directly from the program.</p>
<p><br> When <code>std::terminate</code> is called due to a thrown exception, an implicit try/catch handler is considered active. Thus, calling <code><a href="current_exception.html" title="cpp/error/current exception">std::current_exception</a></code> will return the thrown exception.</p>
<p>In any case, <code>std::terminate</code> calls the currently installed <code><a href="terminate_handler.html" title="cpp/error/terminate handler">std::terminate_handler</a></code>. The default <code><a href="terminate_handler.html" title="cpp/error/terminate handler">std::terminate_handler</a></code> calls <code><a href="../utility/program/abort.html" title="cpp/utility/program/abort">std::abort</a></code>.</p>
<table class="t-rev-begin"> <tr class="t-rev t-until-cxx11">
<td> <p>If a destructor reset the terminate handler during stack unwinding and the unwinding later led to <code>terminate</code> being called, the handler that was installed at the end of the throw expression is the one that will be called. (note: it was ambiguous whether re-throwing applied the new handlers)</p>
</td> <td><span class="t-mark-rev t-until-cxx11">(until C++11)</span></td>
</tr> <tr class="t-rev t-since-cxx11">
<td> <p>If a destructor reset the terminate handler during stack unwinding, it is unspecified which handler is called if the unwinding later led to <code>terminate</code> being called.</p>
</td> <td><span class="t-mark-rev t-since-cxx11">(since C++11)</span></td>
</tr> </table>  <h3 id="Parameters"> Parameters</h3> <p>(none)</p>
<h3 id="Return_value"> Return value</h3> <p>(none)</p>
<h3 id="Notes"> Notes</h3> <p>If the handler mechanism is not wanted, e.g. because it requires atomic operations which may bloat binary size, a direct call to <code><a href="../utility/program/abort.html" title="cpp/utility/program/abort">std::abort</a></code> is preferred when terminating the program abnormally.</p>
<p>Some compiler intrinsics, e.g. <a rel="nofollow" class="external text" href="https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html"><code>__builtin_trap</code></a> (gcc, clang, and icc) or <a rel="nofollow" class="external text" href="https://docs.microsoft.com/en-us/cpp/intrinsics/debugbreak?view=msvc-160"><code>__debugbreak</code></a> (msvc), can be used to terminate the program as fast as possible.</p>
<h3 id="Defect_reports"> Defect reports</h3> <p>The following behavior-changing defect reports were applied retroactively to previously published C++ standards.</p>
<table class="dsctable"> <tr> <th>DR </th> <th>Applied to </th> <th>Behavior as published </th> <th>Correct behavior </th>
</tr> <tr> <td>
<a rel="nofollow" class="external text" href="https://cplusplus.github.io/LWG/issue2111">LWG 2111</a> </td> <td>C++11 </td> <td>effect of calling <code>set_terminate</code> during stack unwinding differs from C++98 and breaks some ABIs </td> <td>made unspecified </td>
</tr>
</table> <h3 id="See_also"> See also</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="terminate_handler.html" title="cpp/error/terminate handler"> <span class="t-lines"><span>terminate_handler</span></span></a></div> </td> <td> the type of the function called by <code>std::terminate</code> <br> <span class="t-mark">(typedef)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="../utility/program/abort.html" title="cpp/utility/program/abort"> <span class="t-lines"><span>abort</span></span></a></div> </td> <td> causes abnormal program termination (without cleaning up) <br> <span class="t-mark">(function)</span>  </td>
</tr> </table>           <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/error/terminate" class="_attribution-link">https://en.cppreference.com/w/cpp/error/terminate</a>
  </p>
</div>
