<p class="_links"><a href="../../dart-async/dart-async-library.html" class="_links-link">dart:async</a></p> <h1>Future&lt;<wbr>T&gt;.error</wbr> constructor  </h1> <section class="multi-line-signature"> Future&lt;<wbr>T&gt;.error</wbr>(<wbr><ol class="parameter-list">
<li>
<a href="../../dart-core/object-class.html">Object</a> error, </li> <li>[<a href="../../dart-core/stacktrace-class.html">StackTrace</a>? stackTrace]</li> </ol>) </wbr></section>  <p>Creates a future that completes with an error.</p> <p>The created future will be completed with an error in a future microtask. This allows enough time for someone to add an error handler on the future. If an error handler isn't added before the future completes, the error will be considered unhandled.</p> <p>Use <a href="../completer-class.html">Completer</a> to create a future and complete it later.</p> <p>Example:</p> <pre class="language-dart" data-language="dart">Future&lt;int&gt; getFuture() {
 return Future.error(Exception('Issue'));
}

final error = await getFuture(); // Throws.</pre>   <h2 id="source">Implementation</h2> <pre class="language-dart" data-language="dart">factory Future.error(Object error, [StackTrace? stackTrace]) {
  // TODO(40614): Remove once non-nullability is sound.
  checkNotNullable(error, "error");
  if (!identical(Zone.current, _rootZone)) {
    AsyncError? replacement = Zone.current.errorCallback(error, stackTrace);
    if (replacement != null) {
      error = replacement.error;
      stackTrace = replacement.stackTrace;
    }
  }
  stackTrace ??= AsyncError.defaultStackTrace(error);
  return new _Future&lt;T&gt;.immediateError(error, stackTrace);
}</pre><div class="_attribution">
  <p class="_attribution-p">
    &copy; 2012 the Dart project authors<br>Licensed under the BSD 3-Clause "New" or "Revised" License.<br>
    <a href="https://api.dart.dev/stable/2.18.5/dart-async/Future/Future.error.html" class="_attribution-link">https://api.dart.dev/stable/2.18.5/dart-async/Future/Future.error.html</a>
  </p>
</div>
